import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import MenuBar from "./components/MenuBar";
import { ThemeProvider } from "./providers/ThemeProvider";
import { PageProvider } from "./providers/PageProvider";
import './globals.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RenanHSilveira",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  function renderConteudo() {
    switch (pagina) {
      case "sobre":
        return <Sobre />;
      case "projetos":
        return <Projetos />;
      default:
        return <Home />;
    }
  }

  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider>
          <PageProvider>
            <MenuBar></MenuBar>
            {children}
          </PageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
